version: '3.8'

volumes:
  local_mysql_data: {}

services:
  backend:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    image: auth_local
    container_name: auth_local
    ports:
      - 8000:8000
    volumes:
      - ./auth:/app
    env_file:
      - ./auth/.env
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7.12
    restart: always
    environment:
      MYSQL_DATABASE: auth
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - local_mysql_data:/var/lib/mysql
    ports:
      - 33066:3306

